# Generated by tools/convert_pv_report_to_fss_tfvars.py.
# Legacy NFS server and storageclass are preserved as freeform tags.

mount_targets = {
  "mt_10_0_2_10" = {
    display_name = "fss-mt-10-0-2-10"
    freeform_tags = {
      legacy_server = "10.0.2.10"
    }
  }
}

filesystems = {
  "pvc_00000008_0008_0008_0008_000000000008" = {
    display_name = "pvc-00000008-0008-0008-0008-000000000008"
    freeform_tags = {
      legacy_pv           = "pvc-00000008-0008-0008-0008-000000000008"
      legacy_server       = "10.0.2.10"
      legacy_storageclass = "front"
      legacy_path         = "/legacy-nas-b/tenant-beta/app-env-c-queue-data-workbench-application-0-pvc-00000008-0008-0008-0008-000000000008"
    }
    exports = {
      primary = {
        mount_target_key = "mt_10_0_2_10"
        path             = "/legacy-nas-b/tenant-beta/app-env-c-queue-data-workbench-application-0-pvc-00000008-0008-0008-0008-000000000008"
      }
    }
  }
  "pvc_00000009_0009_0009_0009_000000000009" = {
    display_name = "pvc-00000009-0009-0009-0009-000000000009"
    freeform_tags = {
      legacy_pv           = "pvc-00000009-0009-0009-0009-000000000009"
      legacy_server       = "10.0.2.10"
      legacy_storageclass = "front"
      legacy_path         = "/legacy-nas-b/tenant-beta/app-env-c-queue-data-workbench-application-1-pvc-00000009-0009-0009-0009-000000000009"
    }
    exports = {
      primary = {
        mount_target_key = "mt_10_0_2_10"
        path             = "/legacy-nas-b/tenant-beta/app-env-c-queue-data-workbench-application-1-pvc-00000009-0009-0009-0009-000000000009"
      }
    }
  }
  "pvc_00000010_0010_0010_0010_000000000010" = {
    display_name = "pvc-00000010-0010-0010-0010-000000000010"
    freeform_tags = {
      legacy_pv           = "pvc-00000010-0010-0010-0010-000000000010"
      legacy_server       = "10.0.2.10"
      legacy_storageclass = "front"
      legacy_path         = "/legacy-nas-b/tenant-beta/app-env-c-workbench-sync-manager-pvc-oms-pvc-00000010-0010-0010-0010-000000000010"
    }
    exports = {
      primary = {
        mount_target_key = "mt_10_0_2_10"
        path             = "/legacy-nas-b/tenant-beta/app-env-c-workbench-sync-manager-pvc-oms-pvc-00000010-0010-0010-0010-000000000010"
      }
    }
  }
  "pvc_00000011_0011_0011_0011_000000000011" = {
    display_name = "pvc-00000011-0011-0011-0011-000000000011"
    freeform_tags = {
      legacy_pv           = "pvc-00000011-0011-0011-0011-000000000011"
      legacy_server       = "10.0.2.10"
      legacy_storageclass = "front"
      legacy_path         = "/legacy-nas-b/tenant-beta/app-env-b-queue-data-workbench-application-0-pvc-00000011-0011-0011-0011-000000000011"
    }
    exports = {
      primary = {
        mount_target_key = "mt_10_0_2_10"
        path             = "/legacy-nas-b/tenant-beta/app-env-b-queue-data-workbench-application-0-pvc-00000011-0011-0011-0011-000000000011"
      }
    }
  }
  "pvc_00000012_0012_0012_0012_000000000012" = {
    display_name = "pvc-00000012-0012-0012-0012-000000000012"
    freeform_tags = {
      legacy_pv           = "pvc-00000012-0012-0012-0012-000000000012"
      legacy_server       = "10.0.2.10"
      legacy_storageclass = "front"
      legacy_path         = "/legacy-nas-b/tenant-beta/app-env-a-queue-data-workbench-application-1-pvc-00000012-0012-0012-0012-000000000012"
    }
    exports = {
      primary = {
        mount_target_key = "mt_10_0_2_10"
        path             = "/legacy-nas-b/tenant-beta/app-env-a-queue-data-workbench-application-1-pvc-00000012-0012-0012-0012-000000000012"
      }
    }
  }
  "pvc_00000013_0013_0013_0013_000000000013" = {
    display_name = "pvc-00000013-0013-0013-0013-000000000013"
    freeform_tags = {
      legacy_pv           = "pvc-00000013-0013-0013-0013-000000000013"
      legacy_server       = "10.0.2.10"
      legacy_storageclass = "front"
      legacy_path         = "/legacy-nas-b/tenant-beta/app-env-a-workbench-sync-manager-pvc-oms-pvc-00000013-0013-0013-0013-000000000013"
    }
    exports = {
      primary = {
        mount_target_key = "mt_10_0_2_10"
        path             = "/legacy-nas-b/tenant-beta/app-env-a-workbench-sync-manager-pvc-oms-pvc-00000013-0013-0013-0013-000000000013"
      }
    }
  }
  "pvc_00000014_0014_0014_0014_000000000014" = {
    display_name = "pvc-00000014-0014-0014-0014-000000000014"
    freeform_tags = {
      legacy_pv           = "pvc-00000014-0014-0014-0014-000000000014"
      legacy_server       = "10.0.2.10"
      legacy_storageclass = "front"
      legacy_path         = "/legacy-nas-b/tenant-beta/app-env-b-queue-data-workbench-sync-manager-0-pvc-00000014-0014-0014-0014-000000000014"
    }
    exports = {
      primary = {
        mount_target_key = "mt_10_0_2_10"
        path             = "/legacy-nas-b/tenant-beta/app-env-b-queue-data-workbench-sync-manager-0-pvc-00000014-0014-0014-0014-000000000014"
      }
    }
  }
  "pvc_00000015_0015_0015_0015_000000000015" = {
    display_name = "pvc-00000015-0015-0015-0015-000000000015"
    freeform_tags = {
      legacy_pv           = "pvc-00000015-0015-0015-0015-000000000015"
      legacy_server       = "10.0.2.10"
      legacy_storageclass = "front"
      legacy_path         = "/legacy-nas-b/tenant-beta/app-env-c-workbench-notification-scope-pvc-00000015-0015-0015-0015-000000000015"
    }
    exports = {
      primary = {
        mount_target_key = "mt_10_0_2_10"
        path             = "/legacy-nas-b/tenant-beta/app-env-c-workbench-notification-scope-pvc-00000015-0015-0015-0015-000000000015"
      }
    }
  }
  "pvc_00000016_0016_0016_0016_000000000016" = {
    display_name = "pvc-00000016-0016-0016-0016-000000000016"
    freeform_tags = {
      legacy_pv           = "pvc-00000016-0016-0016-0016-000000000016"
      legacy_server       = "10.0.2.10"
      legacy_storageclass = "front"
      legacy_path         = "/legacy-nas-b/tenant-beta/app-env-b-workbench-notification-scope-pvc-00000016-0016-0016-0016-000000000016"
    }
    exports = {
      primary = {
        mount_target_key = "mt_10_0_2_10"
        path             = "/legacy-nas-b/tenant-beta/app-env-b-workbench-notification-scope-pvc-00000016-0016-0016-0016-000000000016"
      }
    }
  }
  "pvc_00000017_0017_0017_0017_000000000017" = {
    display_name = "pvc-00000017-0017-0017-0017-000000000017"
    freeform_tags = {
      legacy_pv           = "pvc-00000017-0017-0017-0017-000000000017"
      legacy_server       = "10.0.2.10"
      legacy_storageclass = "front"
      legacy_path         = "/legacy-nas-b/tenant-beta/app-env-a-queue-data-workbench-sync-manager-0-pvc-00000017-0017-0017-0017-000000000017"
    }
    exports = {
      primary = {
        mount_target_key = "mt_10_0_2_10"
        path             = "/legacy-nas-b/tenant-beta/app-env-a-queue-data-workbench-sync-manager-0-pvc-00000017-0017-0017-0017-000000000017"
      }
    }
  }
  "pvc_00000018_0018_0018_0018_000000000018" = {
    display_name = "pvc-00000018-0018-0018-0018-000000000018"
    freeform_tags = {
      legacy_pv           = "pvc-00000018-0018-0018-0018-000000000018"
      legacy_server       = "10.0.2.10"
      legacy_storageclass = "front"
      legacy_path         = "/legacy-nas-b/tenant-beta/app-env-c-queue-data-workbench-sync-manager-0-pvc-00000018-0018-0018-0018-000000000018"
    }
    exports = {
      primary = {
        mount_target_key = "mt_10_0_2_10"
        path             = "/legacy-nas-b/tenant-beta/app-env-c-queue-data-workbench-sync-manager-0-pvc-00000018-0018-0018-0018-000000000018"
      }
    }
  }
  "pvc_00000019_0019_0019_0019_000000000019" = {
    display_name = "pvc-00000019-0019-0019-0019-000000000019"
    freeform_tags = {
      legacy_pv           = "pvc-00000019-0019-0019-0019-000000000019"
      legacy_server       = "10.0.2.10"
      legacy_storageclass = "front"
      legacy_path         = "/legacy-nas-b/tenant-beta/app-env-a-workbench-notification-scope-pvc-00000019-0019-0019-0019-000000000019"
    }
    exports = {
      primary = {
        mount_target_key = "mt_10_0_2_10"
        path             = "/legacy-nas-b/tenant-beta/app-env-a-workbench-notification-scope-pvc-00000019-0019-0019-0019-000000000019"
      }
    }
  }
  "pvc_00000020_0020_0020_0020_000000000020" = {
    display_name = "pvc-00000020-0020-0020-0020-000000000020"
    freeform_tags = {
      legacy_pv           = "pvc-00000020-0020-0020-0020-000000000020"
      legacy_server       = "10.0.2.10"
      legacy_storageclass = "front"
      legacy_path         = "/legacy-nas-b/tenant-beta/app-env-a-queue-data-workbench-application-0-pvc-00000020-0020-0020-0020-000000000020"
    }
    exports = {
      primary = {
        mount_target_key = "mt_10_0_2_10"
        path             = "/legacy-nas-b/tenant-beta/app-env-a-queue-data-workbench-application-0-pvc-00000020-0020-0020-0020-000000000020"
      }
    }
  }
  "pvc_00000021_0021_0021_0021_000000000021" = {
    display_name = "pvc-00000021-0021-0021-0021-000000000021"
    freeform_tags = {
      legacy_pv           = "pvc-00000021-0021-0021-0021-000000000021"
      legacy_server       = "10.0.2.10"
      legacy_storageclass = "front"
      legacy_path         = "/legacy-nas-b/tenant-beta/app-env-b-workbench-sync-manager-pvc-oms-pvc-00000021-0021-0021-0021-000000000021"
    }
    exports = {
      primary = {
        mount_target_key = "mt_10_0_2_10"
        path             = "/legacy-nas-b/tenant-beta/app-env-b-workbench-sync-manager-pvc-oms-pvc-00000021-0021-0021-0021-000000000021"
      }
    }
  }
}

# Parsed source summary.
# Nodes: 7
# Persistent volumes: 14
# Legacy servers: 1
