# Generated by tools/convert_pv_report_to_fss_tfvars.py.
# Legacy NFS server and storageclass are preserved as freeform tags.

mount_targets = {
  "mt_10_0_1_10" = {
    display_name = "fss-mt-10-0-1-10"
    freeform_tags = {
      legacy_server = "10.0.1.10"
    }
  }
}

filesystems = {
  "pvc_00000001_0001_0001_0001_000000000001" = {
    display_name = "pvc-00000001-0001-0001-0001-000000000001"
    freeform_tags = {
      legacy_pv           = "pvc-00000001-0001-0001-0001-000000000001"
      legacy_server       = "10.0.1.10"
      legacy_storageclass = "core"
      legacy_path         = "/legacy-nas-a/tenant-alpha/app-env-b-web-cache-0-pvc-00000001-0001-0001-0001-000000000001"
    }
    exports = {
      primary = {
        mount_target_key = "mt_10_0_1_10"
        path             = "/legacy-nas-a/tenant-alpha/app-env-b-web-cache-0-pvc-00000001-0001-0001-0001-000000000001"
      }
    }
  }
  "pvc_00000002_0002_0002_0002_000000000002" = {
    display_name = "pvc-00000002-0002-0002-0002-000000000002"
    freeform_tags = {
      legacy_pv           = "pvc-00000002-0002-0002-0002-000000000002"
      legacy_server       = "10.0.1.10"
      legacy_storageclass = "core"
      legacy_path         = "/legacy-nas-a/tenant-alpha/platform-monitoring-grafana-storage-pvc-00000002-0002-0002-0002-000000000002"
    }
    exports = {
      primary = {
        mount_target_key = "mt_10_0_1_10"
        path             = "/legacy-nas-a/tenant-alpha/platform-monitoring-grafana-storage-pvc-00000002-0002-0002-0002-000000000002"
      }
    }
  }
  "pvc_00000003_0003_0003_0003_000000000003" = {
    display_name = "pvc-00000003-0003-0003-0003-000000000003"
    freeform_tags = {
      legacy_pv           = "pvc-00000003-0003-0003-0003-000000000003"
      legacy_server       = "10.0.1.10"
      legacy_storageclass = "core"
      legacy_path         = "/legacy-nas-a/tenant-alpha/platform-monitoring-alertmanager-db-0-pvc-00000003-0003-0003-0003-000000000003"
    }
    exports = {
      primary = {
        mount_target_key = "mt_10_0_1_10"
        path             = "/legacy-nas-a/tenant-alpha/platform-monitoring-alertmanager-db-0-pvc-00000003-0003-0003-0003-000000000003"
      }
    }
  }
  "pvc_00000004_0004_0004_0004_000000000004" = {
    display_name = "pvc-00000004-0004-0004-0004-000000000004"
    freeform_tags = {
      legacy_pv           = "pvc-00000004-0004-0004-0004-000000000004"
      legacy_server       = "10.0.1.10"
      legacy_storageclass = "core"
      legacy_path         = "/legacy-nas-a/tenant-alpha/app-env-c-web-cache-0-pvc-00000004-0004-0004-0004-000000000004"
    }
    exports = {
      primary = {
        mount_target_key = "mt_10_0_1_10"
        path             = "/legacy-nas-a/tenant-alpha/app-env-c-web-cache-0-pvc-00000004-0004-0004-0004-000000000004"
      }
    }
  }
  "pvc_00000005_0005_0005_0005_000000000005" = {
    display_name = "pvc-00000005-0005-0005-0005-000000000005"
    freeform_tags = {
      legacy_pv           = "pvc-00000005-0005-0005-0005-000000000005"
      legacy_server       = "10.0.1.10"
      legacy_storageclass = "core"
      legacy_path         = "/legacy-nas-a/tenant-alpha/platform-monitoring-prometheus-db-0-pvc-00000005-0005-0005-0005-000000000005"
    }
    exports = {
      primary = {
        mount_target_key = "mt_10_0_1_10"
        path             = "/legacy-nas-a/tenant-alpha/platform-monitoring-prometheus-db-0-pvc-00000005-0005-0005-0005-000000000005"
      }
    }
  }
  "pvc_00000006_0006_0006_0006_000000000006" = {
    display_name = "pvc-00000006-0006-0006-0006-000000000006"
    freeform_tags = {
      legacy_pv           = "pvc-00000006-0006-0006-0006-000000000006"
      legacy_server       = "10.0.1.10"
      legacy_storageclass = "core"
      legacy_path         = "/legacy-nas-a/tenant-alpha/app-env-a-web-cache-0-pvc-00000006-0006-0006-0006-000000000006"
    }
    exports = {
      primary = {
        mount_target_key = "mt_10_0_1_10"
        path             = "/legacy-nas-a/tenant-alpha/app-env-a-web-cache-0-pvc-00000006-0006-0006-0006-000000000006"
      }
    }
  }
}

# Parsed source summary.
# Nodes: 7
# Persistent volumes: 6
# Legacy servers: 1
