#!/usr/bin/env python3
"""Convert legacy Kubernetes/NFS PV report files to fss_stack_sprint12 tfvars."""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class Node:
    name: str
    status: str
    roles: str
    age: str
    version: str
    zone: str


@dataclass(frozen=True)
class PersistentVolume:
    name: str
    path: str
    server: str
    storageclass: str


class ConversionError(Exception):
    pass


NODE_RE = re.compile(r"^(?P<name>\S+)\s+(?P<status>\S+)\s+(?P<roles>\S+)\s+(?P<age>\S+)\s+(?P<version>\S+)\s+(?P<zone>\S+)$")


def terraform_key(value: str, prefix: str = "") -> str:
    key = re.sub(r"[^0-9A-Za-z_]", "_", value.strip())
    key = re.sub(r"_+", "_", key).strip("_").lower()
    if not key:
        key = "item"
    if key[0].isdigit():
        key = f"{prefix}{key}" if prefix else f"item_{key}"
    elif prefix and not key.startswith(prefix):
        key = f"{prefix}{key}"
    return key


def hcl_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def parse_report(text: str) -> tuple[list[Node], list[PersistentVolume]]:
    nodes: list[Node] = []
    pvs: list[PersistentVolume] = []
    current: dict[str, str] | None = None

    def finish_current(line_number: int) -> None:
        nonlocal current
        if current is None:
            return
        missing = [field for field in ("name", "path", "server", "storageclass") if not current.get(field)]
        if missing:
            label = current.get("name", "<unknown>")
            raise ConversionError(f"incomplete PV block for {label} before line {line_number}: missing {', '.join(missing)}")
        pvs.append(
            PersistentVolume(
                name=current["name"],
                path=current["path"],
                server=current["server"],
                storageclass=current["storageclass"],
            )
        )
        current = None

    for line_number, raw_line in enumerate(text.splitlines(), start=1):
        line = raw_line.strip()
        if not line or line == "##########":
            continue
        if line.startswith("NAME "):
            finish_current(line_number)
            continue
        if line.startswith("PV Name:"):
            finish_current(line_number)
            name = line.split(":", 1)[1].strip()
            if not name:
                raise ConversionError(f"empty PV Name at line {line_number}")
            current = {"name": name}
            continue
        if line.startswith("path:"):
            if current is None:
                raise ConversionError(f"path outside PV block at line {line_number}")
            current["path"] = line.split(":", 1)[1].strip()
            continue
        if line.startswith("server:"):
            if current is None:
                raise ConversionError(f"server outside PV block at line {line_number}")
            current["server"] = line.split(":", 1)[1].strip()
            continue
        if line.startswith("storageclass:"):
            if current is None:
                raise ConversionError(f"storageclass outside PV block at line {line_number}")
            current["storageclass"] = line.split(":", 1)[1].strip()
            continue

        node_match = NODE_RE.match(line)
        if node_match and node_match.group("status") == "Ready":
            finish_current(line_number)
            nodes.append(Node(**node_match.groupdict()))
            continue

        raise ConversionError(f"unrecognized line {line_number}: {raw_line}")

    finish_current(len(text.splitlines()) + 1)
    if not pvs:
        raise ConversionError("report contains no PV blocks")
    return nodes, pvs


def unique_key(base: str, used: set[str]) -> str:
    key = base
    counter = 2
    while key in used:
        key = f"{base}_{counter}"
        counter += 1
    used.add(key)
    return key


def render_tfvars(nodes: list[Node], pvs: list[PersistentVolume]) -> str:
    servers = list(dict.fromkeys(pv.server for pv in pvs))
    used_mount_keys: set[str] = set()
    mount_key_by_server = {
        server: unique_key(terraform_key(server, "mt_"), used_mount_keys)
        for server in servers
    }

    used_fs_keys: set[str] = set()
    fs_key_by_pv = {
        pv.name: unique_key(terraform_key(pv.name), used_fs_keys)
        for pv in pvs
    }

    out: list[str] = []
    out.append("# Generated by tools/convert_pv_report_to_fss_tfvars.py.")
    out.append("# Legacy NFS server and storageclass are preserved as freeform tags.")
    out.append("")
    out.append("mount_targets = {")
    for server in servers:
        key = mount_key_by_server[server]
        out.append(f"  {hcl_string(key)} = {{")
        out.append(f"    display_name = {hcl_string('fss-' + key.replace('_', '-'))}")
        out.append("    freeform_tags = {")
        out.append(f"      legacy_server = {hcl_string(server)}")
        out.append("    }")
        out.append("  }")
    out.append("}")
    out.append("")
    out.append("filesystems = {")
    for pv in pvs:
        fs_key = fs_key_by_pv[pv.name]
        mount_key = mount_key_by_server[pv.server]
        out.append(f"  {hcl_string(fs_key)} = {{")
        out.append(f"    display_name = {hcl_string(pv.name)}")
        out.append("    freeform_tags = {")
        out.append(f"      legacy_pv           = {hcl_string(pv.name)}")
        out.append(f"      legacy_server       = {hcl_string(pv.server)}")
        out.append(f"      legacy_storageclass = {hcl_string(pv.storageclass)}")
        out.append(f"      legacy_path         = {hcl_string(pv.path)}")
        out.append("    }")
        out.append("    exports = {")
        out.append("      primary = {")
        out.append(f"        mount_target_key = {hcl_string(mount_key)}")
        out.append(f"        path             = {hcl_string(pv.path)}")
        out.append("      }")
        out.append("    }")
        out.append("  }")
    out.append("}")
    out.append("")
    out.append("# Parsed source summary.")
    out.append(f"# Nodes: {len(nodes)}")
    out.append(f"# Persistent volumes: {len(pvs)}")
    out.append(f"# Legacy servers: {len(servers)}")
    return "\n".join(out) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=Path, help="Legacy PV report file.")
    parser.add_argument("-o", "--output", type=Path, help="Output .auto.tfvars path. Defaults to stdout.")
    args = parser.parse_args(argv)

    try:
        nodes, pvs = parse_report(args.input.read_text(encoding="utf-8"))
        rendered = render_tfvars(nodes, pvs)
    except (OSError, ConversionError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(rendered, encoding="utf-8")
    else:
        print(rendered, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
